ArkEcosystem/platform-sdk

packages/platform-sdk-ada/src/manifest.ts
packages/platform-sdk-ark/__tests__/services/client.test.ts
packages/platform-sdk-ark/src/manifest.ts
packages/platform-sdk-ark/src/services/client.ts
packages/platform-sdk-atom/src/manifest.ts
packages/platform-sdk-atom/src/services/client.ts
packages/platform-sdk-btc/src/manifest.ts
packages/platform-sdk-btc/src/services/client.ts
packages/platform-sdk-eos/src/manifest.ts
packages/platform-sdk-eos/src/services/client.ts
packages/platform-sdk-eth/src/manifest.ts
packages/platform-sdk-eth/src/services/client.ts
packages/platform-sdk-lsk/__tests__/services/client.test.ts
packages/platform-sdk-lsk/src/manifest.ts
packages/platform-sdk-lsk/src/services/client.ts
packages/platform-sdk-neo/src/manifest.ts
packages/platform-sdk-neo/src/services/client.ts
packages/platform-sdk-trx/src/manifest.ts
packages/platform-sdk-trx/src/services/client.ts
packages/platform-sdk-xmr/src/manifest.ts
packages/platform-sdk-xmr/src/services/client.ts
packages/platform-sdk-xrp/src/manifest.ts
packages/platform-sdk-xrp/src/services/client.ts
packages/platform-sdk/src/contracts/coins/client.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/102
The `getTransactions` and `getWallets` methods will instead merge their behaviour into themselves.

refactor: drop `ClientService#searchTransactions` and `ClientService#searchWallets`

---

packages/platform-sdk-ark/__tests__/__fixtures__/client/syncing.json
packages/platform-sdk-ark/__tests__/services/client.test.ts
packages/platform-sdk-ark/__tests__/services/transaction.test.ts
packages/platform-sdk-ark/src/services/client.ts
packages/platform-sdk-ark/src/services/transaction.ts
packages/platform-sdk-atom/src/services/client.ts
packages/platform-sdk-atom/src/services/identity.ts
packages/platform-sdk-btc/src/services/client.ts
packages/platform-sdk-eos/src/services/client.ts
packages/platform-sdk-eth/src/services/client.ts
packages/platform-sdk-lsk/src/services/client.ts
packages/platform-sdk-neo/src/services/client.ts
packages/platform-sdk-trx/src/services/client.ts
packages/platform-sdk-xmr/src/services/client.ts
packages/platform-sdk-xrp/src/services/client.ts
packages/platform-sdk/src/contracts/coins/client.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/127
The ARK crypto package is now autoconfigured based on the peer that is being used initially.

refactor: remove `ClientService#configuration`

---

packages/platform-sdk/src/utils/dayjs.ts

Importing the plugin globally forces the compiler to add it to the declaration file.
Fixes #110

fix: utc declaration for dayjs

---

docs/coins/index.md
packages/platform-sdk-ark/__tests__/dto/transaction.test.ts
packages/platform-sdk-ark/src/dto/transaction.ts
packages/platform-sdk-atom/__tests__/dto/transaction.test.ts
packages/platform-sdk-atom/__tests__/services/client.test.ts
packages/platform-sdk-atom/src/dto/transaction.ts
packages/platform-sdk-btc/__tests__/dto/transaction.test.ts
packages/platform-sdk-btc/__tests__/services/client.test.ts
packages/platform-sdk-btc/src/dto/transaction.ts
packages/platform-sdk-eos/src/dto/transaction.ts
packages/platform-sdk-eth/__tests__/dto/transaction.test.ts
packages/platform-sdk-eth/__tests__/services/client.test.ts
packages/platform-sdk-eth/src/dto/transaction.ts
packages/platform-sdk-lsk/__tests__/dto/transaction.test.ts
packages/platform-sdk-lsk/src/dto/transaction.ts
packages/platform-sdk-neo/__tests__/dto/transaction.test.ts
packages/platform-sdk-neo/__tests__/services/client.test.ts
packages/platform-sdk-neo/src/dto/transaction.ts
packages/platform-sdk-trx/src/dto/transaction.ts
packages/platform-sdk-xlm/__tests__/services/client.test.ts
packages/platform-sdk-xlm/src/dto/transaction.ts
packages/platform-sdk-xmr/src/dto/transaction.ts
packages/platform-sdk-xrp/__tests__/dto/transaction.test.ts
packages/platform-sdk-xrp/__tests__/services/client.test.ts
packages/platform-sdk-xrp/src/dto/transaction.ts
packages/platform-sdk/src/contracts/coins/data.ts
packages/platform-sdk/src/dto/transaction.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/195

refactor: always treat `nonce` as `BigNumber`

---

packages/platform-sdk-ark/__tests__/dto/transaction.test.ts
packages/platform-sdk-ark/src/dto/transaction.ts
packages/platform-sdk-atom/__tests__/dto/transaction.test.ts
packages/platform-sdk-atom/__tests__/services/client.test.ts
packages/platform-sdk-atom/src/dto/transaction.ts
packages/platform-sdk-btc/__tests__/dto/transaction.test.ts
packages/platform-sdk-btc/__tests__/services/client.test.ts
packages/platform-sdk-btc/src/dto/transaction.ts
packages/platform-sdk-eos/src/dto/transaction.ts
packages/platform-sdk-eth/__tests__/dto/transaction.test.ts
packages/platform-sdk-eth/__tests__/services/client.test.ts
packages/platform-sdk-eth/src/dto/transaction.ts
packages/platform-sdk-lsk/__tests__/dto/transaction.test.ts
packages/platform-sdk-lsk/src/dto/transaction.ts
packages/platform-sdk-neo/__tests__/dto/transaction.test.ts
packages/platform-sdk-neo/__tests__/services/client.test.ts
packages/platform-sdk-neo/src/dto/transaction.ts
packages/platform-sdk-trx/src/dto/transaction.ts
packages/platform-sdk-xlm/__tests__/services/client.test.ts
packages/platform-sdk-xlm/src/dto/transaction.ts
packages/platform-sdk-xmr/src/dto/transaction.ts
packages/platform-sdk-xrp/__tests__/dto/transaction.test.ts
packages/platform-sdk-xrp/__tests__/services/client.test.ts
packages/platform-sdk-xrp/src/dto/transaction.ts
packages/platform-sdk/src/contracts/coins/data.ts
packages/platform-sdk/src/dto/transaction.ts

The `nonce` isn't relevant outside of signing transactions.

refactor: remove `TransactionData#nonce` method

---

packages/platform-sdk-ark/__tests__/services/fee.test.ts
packages/platform-sdk-ark/src/services/fee.ts
packages/platform-sdk/src/contracts/coins/fee.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/225

fix(ark): return magistrate fees

---

packages/platform-sdk-xrp/__tests__/services/client.test.ts
packages/platform-sdk-xrp/src/dto/transaction.ts
packages/platform-sdk-xrp/src/services/client.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/84

fix(xrp): only list `XRP` transactions

---

WALLET_INSTRUCTIONS.md
packages/platform-sdk-ark/src/services/fee.ts
packages/platform-sdk-eth/src/services/transaction.ts
packages/platform-sdk-xrp/__tests__/services/client.test.ts
packages/platform-sdk-xrp/__tests__/services/ledger.test.ts
packages/platform-sdk-xrp/src/services/ledger.ts
packages/platform-sdk/src/contracts/coins/transaction.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/232

feat(eth): support transferring `ERC20` tokens

---

packages/platform-sdk-coincap/__tests__/tracker.test.ts
packages/platform-sdk-lsk/src/services/ledger.ts
packages/platform-sdk/src/coins/coin.ts
packages/platform-sdk/src/coins/contracts.ts
packages/platform-sdk/src/coins/factory.ts
packages/platform-sdk/src/coins/guard.ts

The `CoinFactory` now creates a `Coin` instance that exposes all services and data of a concrete coin implementation. This makes the `CoinFactory` a real factory and things easier to test.

refactor(sdk): implement `Coin` to slim down `CoinFactory`

---

packages/platform-sdk-intl/src/datetime.ts

Require `dayjs` locale files explicitly using full file paths (adding `.js` suffix).
Remove duplicate imports for `dayjs` and plugins.
Prevents Typescript compilation errors on forcing type inclusion when platform-sdk is used as a third-party package (seen in `mobile-wallet` angular compilation).

chore: fix type inclusion errors

---

CHANGELOG.md
packages/platform-sdk-profiles/__tests__/contact-repository.test.ts
packages/platform-sdk-profiles/__tests__/contact.test.ts
packages/platform-sdk-profiles/__tests__/env.test.ts
packages/platform-sdk-profiles/__tests__/migrator.test.ts
packages/platform-sdk-profiles/__tests__/profile-repository.test.ts
packages/platform-sdk-profiles/__tests__/profile.test.ts
packages/platform-sdk-profiles/src/contact-repository.ts
packages/platform-sdk-profiles/src/contact.ts
packages/platform-sdk-profiles/src/contracts.ts
packages/platform-sdk-profiles/src/env.ts
packages/platform-sdk-profiles/src/index.ts
packages/platform-sdk-profiles/src/migrator.ts
packages/platform-sdk-profiles/src/profile-repository.ts
packages/platform-sdk-profiles/src/profile.ts
packages/platform-sdk-profiles/src/profiles.ts
packages/platform-sdk-support/src/bignumber.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/351

feat(profiles): implement `Contacts`

---

packages/platform-sdk-profiles/src/profile.ts
packages/platform-sdk-profiles/src/wallet-repository.ts
packages/platform-sdk-profiles/src/wallet.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/376

feat(profiles): automatically persist wallets after CRUD operations

---

packages/platform-sdk-profiles/__tests__/wallet.test.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/352

test(profiles): cover that custom `slip44` can be used

---

packages/platform-sdk-profiles/src/contracts.ts
packages/platform-sdk-profiles/src/profile.ts
packages/platform-sdk-profiles/src/wallet.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/396
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/395

chore(profiles): add `ProfileStruct` and `WalletStruct` contracts

---

packages/platform-sdk-intl/__tests__/currency.test.ts
packages/platform-sdk-intl/src/currency.ts
packages/platform-sdk-intl/src/index.ts

Implements a way to parse currency strings to get the raw numbers from it. Requires to pass in a `magnitude` to limit the decimal numbers but defaults to 8 for the magnitude.

feat(intl): implement `Currency#fromString` to parse currency strings

---

packages/platform-sdk-atom/src/services/identity/address.ts
packages/platform-sdk-atom/src/services/identity/index.ts
packages/platform-sdk-atom/src/services/identity/keys.ts
packages/platform-sdk-atom/src/services/identity/private-key.ts
packages/platform-sdk-atom/src/services/identity/public-key.ts
packages/platform-sdk-eth/src/services/identity/address.ts
packages/platform-sdk-eth/src/services/identity/index.ts
packages/platform-sdk-eth/src/services/identity/keys.ts
packages/platform-sdk-eth/src/services/identity/private-key.ts
packages/platform-sdk-eth/src/services/identity/public-key.ts
packages/platform-sdk-xrp/src/services/client.ts
packages/platform-sdk-xrp/src/services/ledger.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/458
Only peers will not be used by reference because some coins use WebSockets or require peers in several places which would lead to having to implement some kind of watchers to recreate all of those instances. In those cases, it is advised to simply recreate the whole coin instance to ensure that all previous instances are destroyed and won't interfere with the new one.

refactor: use `Coins.Config` by reference

---

packages/platform-sdk-profiles/__tests__/profile.test.ts
packages/platform-sdk-profiles/__tests__/repositories/wallet-repository.test.ts
packages/platform-sdk-profiles/__tests__/wallet.test.ts
packages/platform-sdk-profiles/src/profile.ts
packages/platform-sdk-profiles/src/repositories/contact-repository.ts
packages/platform-sdk-profiles/src/repositories/notification-repository.ts
packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
packages/platform-sdk-profiles/src/wallet.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/466

feat(profiles): add profile aggregates

---

packages/platform-sdk-ada/src/services/multi-signature.ts
packages/platform-sdk-ark/src/services/index.ts
packages/platform-sdk-ark/src/services/multi-signature.ts
packages/platform-sdk-atom/src/services/index.ts
packages/platform-sdk-atom/src/services/multi-signature.ts
packages/platform-sdk-btc/src/services/index.ts
packages/platform-sdk-btc/src/services/multi-signature.ts
packages/platform-sdk-eos/src/services/index.ts
packages/platform-sdk-eos/src/services/multi-signature.ts
packages/platform-sdk-eth/src/services/index.ts
packages/platform-sdk-eth/src/services/multi-signature.ts
packages/platform-sdk-lsk/src/services/index.ts
packages/platform-sdk-lsk/src/services/multi-signature.ts
packages/platform-sdk-neo/src/services/index.ts
packages/platform-sdk-neo/src/services/multi-signature.ts
packages/platform-sdk-trx/src/services/index.ts
packages/platform-sdk-trx/src/services/multi-signature.ts
packages/platform-sdk-xlm/src/services/index.ts
packages/platform-sdk-xlm/src/services/multi-signature.ts
packages/platform-sdk-xmr/src/services/index.ts
packages/platform-sdk-xmr/src/services/multi-signature.ts
packages/platform-sdk-xrp/src/services/index.ts
packages/platform-sdk-xrp/src/services/multi-signature.ts
packages/platform-sdk/src/coins/coin-factory.ts
packages/platform-sdk/src/coins/coin.ts
packages/platform-sdk/src/coins/contracts.ts
packages/platform-sdk/src/contracts/coins/index.ts
packages/platform-sdk/src/contracts/coins/multi-signature.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/479

feat: implement `MultiSignatureService`

---

packages/platform-sdk-intl/__tests__/datetime.test.ts
packages/platform-sdk-intl/src/datetime.ts

https://day.js.org/docs/en/display/difference

fix(intl): use `day` instead of `date` for differences

---

packages/platform-sdk-profiles/src/repositories/setting-repository.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/534

fix(profiles): validate data in `SettingRepository#fill`

---

packages/platform-sdk-profiles/src/env.test.ts
packages/platform-sdk-profiles/src/env.ts
packages/platform-sdk-profiles/src/network.test.ts
packages/platform-sdk-profiles/src/network.ts
packages/platform-sdk/src/coins/contracts.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/544

feat(profiles): implement `NetworkData`

---

packages/platform-sdk-profiles/src/index.ts

Export the network file in `platform-sdk-profiles` to use `NetworkData`.

fix(profiles): export `NetworkData`

---

packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts
packages/platform-sdk-profiles/src/repositories/profile-repository.ts

Adjusts the `all()` method and adds a `keys()` and `values()` method to the profile repository to be in line with the other repositories.

refactor: streamline profile repository methods

---

packages/platform-sdk-profiles/src/profile.ts
packages/platform-sdk-profiles/src/repositories/contact-repository.test.ts
packages/platform-sdk-profiles/src/repositories/contact-repository.ts

Adds checks to ensure the uniqueness of a contacts name during creation and update.

fix(profiles): ensure uniqueness of contact name

---

packages/platform-sdk-support/src/bignumber.ts

According to https://mikemcl.github.io/bignumber.js/#toFix `num.toFixed() !== num.toFixed(0)`.

fix(support): call `toFixed` with argument if argument is 0

---

packages/platform-sdk-ark/src/services/transaction.test.ts
packages/platform-sdk-ark/src/services/transaction.ts
packages/platform-sdk-atom/src/services/transaction.test.ts
packages/platform-sdk-eos/src/services/transaction.ts
packages/platform-sdk-lsk/src/services/transaction.test.ts
packages/platform-sdk-trx/src/services/transaction.test.ts
packages/platform-sdk-trx/src/services/transaction.ts
packages/platform-sdk-xlm/src/services/client.test.ts
packages/platform-sdk-xlm/src/services/transaction.test.ts
packages/platform-sdk/src/contracts/coins/transaction.ts

> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/636

feat: verify that expected and actual sender of transactions are a match

---

packages/platform-sdk-profiles/src/environment/env.ts

This will enable to register coins at runtime through for example plugins.

feat(profiles): implement `Environment#registerCoin`

---

packages/platform-sdk-profiles/src/profiles/aggregates/registration-aggregate.test.ts
packages/platform-sdk-profiles/src/profiles/aggregates/registration-aggregate.ts
packages/platform-sdk-profiles/test/fixtures/client/registrations/all.json
packages/platform-sdk-profiles/test/fixtures/client/registrations/business.json
packages/platform-sdk-profiles/test/fixtures/client/registrations/core-plugins.json
packages/platform-sdk-profiles/test/fixtures/client/registrations/desktop-plugins.json
packages/platform-sdk-profiles/test/fixtures/wallets/D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb.json

* Use `syncedWallet.client().transactions()` instead of `syncedWallet.transactions()` to fetch registration txs, omitting the `addresses` request param, that was returning empty data.
* Add fixtures and registration aggregate tests

fix(profiles): fix profile registration aggregate query params

---

packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts
packages/platform-sdk-profiles/src/wallets/wallet.models.ts
packages/platform-sdk-profiles/src/wallets/wallet.test.ts
packages/platform-sdk-profiles/src/wallets/wallet.ts

- Stores the exchange currency in addition to the exchange rate on a wallet.
- Updates the market service to fetch each coins exchange rate only once per profile.

feat(profiles): store exchange currency in wallet data

---

packages/platform-sdk-profiles/src/environment/env.test.ts
packages/platform-sdk-profiles/src/profiles/profile.ts
packages/platform-sdk-profiles/src/repositories/profile-repository.ts

Sets the default values when creating a profile, as to not rely on frontend applications to do that.

refactor(profiles): set defaults when creating profile

---

packages/platform-sdk-profiles/src/environment/env.test.ts
packages/platform-sdk-profiles/src/profiles/profile.test.ts
packages/platform-sdk-profiles/src/profiles/profile.ts

The default avatar should not be stored.

fix(profiles): do not set avatar during initialization

---

packages/platform-sdk-news/src/blockfolio.ts

Passes an array of categories to the signals endpoint.

refactor(news): pass categories as array to signals endpoint

---

packages/platform-sdk-profiles/src/repositories/notification-repository.test.ts
packages/platform-sdk-profiles/src/repositories/notification-repository.ts

- Return array of `NotificationsWithId` from read/unread methods instead of object
- Use `NotificationsWithId` as return type instead of `Notification`
- Add coverage

refactor: adjust return types in notifications repo

---

packages/platform-sdk-profiles/src/environment/env.test.ts
packages/platform-sdk-profiles/src/repositories/notification-repository.test.ts
packages/platform-sdk-profiles/src/repositories/notification-repository.ts

* Add `type: string` field in `Notification` for categorization
* Add `meta: any` field in `Notification` to store additional required data.
* Add tests

refactor(notifications): extend `Notification` type

---

packages/platform-sdk-lsk/src/services/client.ts

Removes the hardcoded API limit and sorts the transactions by timestamp by default.

refactor(lsk): don't enforce api limit and sort tx by timestamp

---

packages/platform-sdk-support/src/bignumber.test.ts
packages/platform-sdk-support/src/bignumber.ts

Adds helper methods to expose the `isZero` and `isNegative` methods.

feat(support): implement `BigNumber#isNegative` and `BigNumber#isZero`

---

packages/platform-sdk-ark/src/services/client.test.ts
packages/platform-sdk-ark/src/services/client.ts
packages/platform-sdk/src/contracts/coins/client.ts

Fixes query parameters used in the aggregate entity service.

fix(ark): use searchParams instead of body for Core 3.0

---

packages/platform-sdk-ark/src/services/identity/address.ts

Validates an ARK address before querying the NEO network for it to avoid any bad input.

fix(ark): validate address before checking neo network

---

packages/platform-sdk-ark/src/services/client.ts

In Core 3.0 the `vote` attribute is present only under the `attributes` object, while in 2.7 it is also available at the root level. This change therefore works for both 2.7 and 3.0.
```
// 2.7
{
attributes: {
vote: "...",
},
vote: "...",
}
// 3.0
{
attributes: {
vote: "...",
},
}
```

fix(ark): get votes from attributes object

---

packages/platform-sdk-ark/src/dto/wallet.ts
packages/platform-sdk-atom/src/dto/wallet.ts
packages/platform-sdk-btc/src/dto/wallet.ts
packages/platform-sdk-eos/src/dto/wallet.ts
packages/platform-sdk-eth/src/dto/wallet.ts
packages/platform-sdk-lsk/src/dto/wallet.ts
packages/platform-sdk-neo/src/dto/wallet.ts
packages/platform-sdk-trx/src/dto/wallet.ts
packages/platform-sdk-xlm/src/dto/wallet.ts
packages/platform-sdk-xmr/src/dto/wallet.ts
packages/platform-sdk-xrp/src/dto/wallet.ts
packages/platform-sdk/src/contracts/coins/data.ts
packages/platform-sdk/src/dto/wallet.ts

Required to verify that a mnemonic matches the second signature.

feat: implement `WalletData#secondPublicKey`

---

packages/platform-sdk-lsk/src/services/client.ts

fix(lsk): off by one error in api pagination offset

---

packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.test.ts
packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts
packages/platform-sdk-profiles/src/wallets/wallet.ts

Right now the wallet fetches the exchange rate for all coins, live or not. With these change the respective methods return early instead of fetching the rate for non-live coins.

refactor: fetch exchange rates only for live coins

---

packages/platform-sdk-profiles/src/wallets/wallet.ts

Calls the Networks `cannot` method in the Wallets `cannot` helper.

fix(profiles): call correct method in `Wallet#cannot`

---

packages/platform-sdk/src/coins/coin-factory.ts

This change is somewhat breaking for internals because it has to be kept in mind that the services are not bootstrapped sequentially. This means you can't create services that depend on each other if they are dependent on HTTP requests being completed.

perf(sdk): use `Promise.all` to construct coin services

---

packages/platform-sdk-profiles/src/repositories/profile-repository.ts

As a side-effect of https://github.com/ArkEcosystem/platform-sdk/commit/d14138c44bf28122e9f0635517d591901007535a we can now also restore contacts faster because they can reuse pre-synced coin instances.

perf(profiles): restore wallets before contacts

---

packages/platform-sdk-ark/src/service-provider.ts
packages/platform-sdk-ark/src/services/peer.test.ts
packages/platform-sdk-ark/src/services/peer.ts

Safe 1 unnecessary request because we can already compare the tokens earlier.

perf(ark): compare network tokens after retrieving the crypto configuration

---

packages/platform-sdk/src/http/response.ts

Responses could also be arrays instead of objects.

refactor(sdk): make `Response#json` return type variable

---

packages/platform-sdk-profiles/src/dto/transaction.test.ts
packages/platform-sdk-profiles/src/dto/transaction.ts
packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.test.ts
packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts
packages/platform-sdk-profiles/src/wallets/wallet.models.ts
packages/platform-sdk-profiles/src/wallets/wallet.ts

Also resolves an inconsistency where satoshis were returned as `v / 1e8` even if they weren't converted. Converted values are returned as `v / 1e8` and the original values will be returned as `v` without modifications.

feat(profiles): implement `TransactionData#convertedAmount|fee` 

---

packages/platform-sdk-profiles/src/dto/transaction.test.ts
packages/platform-sdk-profiles/src/dto/transaction.ts

Prevent from throwing type error: `memo is not a function` when calling `transaction.memo()` for transaction types that don't have it. Return undefined instead.

fix(profiles): Transaction#memo return undefined for types that don't support memo

---

packages/platform-sdk-profiles/src/wallets/wallet.models.ts
packages/platform-sdk-profiles/src/wallets/wallet.test.ts
packages/platform-sdk-profiles/src/wallets/wallet.ts

Implements a `knownWallet` method to easily retrieve the known name of a wallet.

feat(profiles): implement `ReadWriteWallet#knownName`

---

packages/platform-sdk-profiles/src/plugins/plugin-registry.models.ts
packages/platform-sdk-profiles/src/plugins/plugin-repository.test.ts
packages/platform-sdk-profiles/src/plugins/plugin-repository.ts
packages/platform-sdk/src/coins/network-repository.test.ts

MSQ used unsigned integers for IDs but NPM uses strings like `"_id": "@dated/transaction-export-plugin"`.

refactor(profiles): change plugin ID type from `number` to `string`

---

packages/platform-sdk-ada/src/services/ledger.ts
packages/platform-sdk-ark/src/services/ledger.test.ts
packages/platform-sdk-ark/src/services/ledger.ts
packages/platform-sdk-atom/src/services/ledger.test.ts
packages/platform-sdk-atom/src/services/ledger.ts
packages/platform-sdk-btc/src/services/ledger.test.ts
packages/platform-sdk-btc/src/services/ledger.ts
packages/platform-sdk-eos/src/services/ledger.test.ts
packages/platform-sdk-eos/src/services/ledger.ts
packages/platform-sdk-eth/src/services/ledger.test.ts
packages/platform-sdk-eth/src/services/ledger.ts
packages/platform-sdk-lsk/src/services/ledger.test.ts
packages/platform-sdk-lsk/src/services/ledger.ts
packages/platform-sdk-neo/src/services/ledger.test.ts
packages/platform-sdk-neo/src/services/ledger.ts
packages/platform-sdk-trx/src/services/ledger.test.ts
packages/platform-sdk-trx/src/services/ledger.ts
packages/platform-sdk-xlm/src/services/ledger.test.ts
packages/platform-sdk-xlm/src/services/ledger.ts
packages/platform-sdk-xrp/src/services/ledger.test.ts
packages/platform-sdk-xrp/src/services/ledger.ts
packages/platform-sdk/src/contracts/coins/ledger.ts

These methods are implementation details and their usage should be determined internally based on network configurations as only ARK has a distinction between schnorr and non-schnorr signing.

refactor(sdk): remove `signTransactionWithSchnorr` and `signMessageWithSchnorr`

---

packages/platform-sdk-ark/src/services/known-wallets.test.ts
packages/platform-sdk-ark/src/services/known-wallets.ts

The known wallets should be in the form of an array, if this is not the case, an empty array should be returned instead.

refactor(ark): return empty list if known wallets response is not an array

---

packages/platform-sdk-profiles/src/profiles/aggregates/transaction-aggregate.test.ts
packages/platform-sdk-profiles/src/profiles/aggregates/transaction-aggregate.ts

Aggregate transactions by wallet addresses if provided in `profile.transactionAggregate()`

feat(profiles): use optional addresses param in transaction aggregate

---

packages/platform-sdk-ark/src/dto/transaction.ts
packages/platform-sdk-atom/src/dto/transaction.ts
packages/platform-sdk-avax/src/dto/transaction.ts
packages/platform-sdk-btc/src/dto/transaction.ts
packages/platform-sdk-eos/src/dto/transaction.ts
packages/platform-sdk-eth/src/dto/transaction.ts
packages/platform-sdk-lsk/src/dto/transaction.ts
packages/platform-sdk-neo/src/dto/transaction.ts
packages/platform-sdk-profiles/src/dto/transaction.test.ts
packages/platform-sdk-profiles/src/dto/transaction.ts
packages/platform-sdk-profiles/src/wallets/wallet.ts
packages/platform-sdk-trx/src/dto/transaction.ts
packages/platform-sdk-xlm/src/dto/transaction.ts
packages/platform-sdk-xrp/src/dto/transaction.ts
packages/platform-sdk/src/contracts/coins/data.ts
packages/platform-sdk/src/dto/transaction.test.ts
packages/platform-sdk/src/dto/transaction.ts

These methods are required for coins that make use of UTXO. The data will have to be normalised in a separate PR.

feat(sdk): implement `TransactionData#inputs/outputs`

---

packages/platform-sdk-ada/src/services/client.ts
packages/platform-sdk-ark/src/services/client.ts
packages/platform-sdk-atom/src/services/client.ts
packages/platform-sdk-avax/src/services/client.ts
packages/platform-sdk-btc/src/services/client.ts
packages/platform-sdk-dot/src/services/client.ts
packages/platform-sdk-eos/src/services/client.ts
packages/platform-sdk-eth/src/services/client.ts
packages/platform-sdk-lsk/src/services/client.ts
packages/platform-sdk-neo/src/services/client.ts
packages/platform-sdk-trx/src/services/client.ts
packages/platform-sdk-xlm/src/services/client.ts
packages/platform-sdk-xrp/src/services/client.ts
packages/platform-sdk/src/contracts/coins/client.ts

Some coins require additional information to retrieve transactions. Initially this will be limited to a `walletId` property which is required by ADA. A separate PR will implement the storage for this value.

refactor: support additional input for `ClientService#transaction`

---

packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts

When calling `profile.aggregate()` with multiple addresses, the wrong `addresses` array is passed in each wallets query, resulting in having the requests of most of the wallets fail because of the wrong address. This PR ensures that `wallet.fetchTransactions` has the correct address of the wallet instance

fix: allow multiple addresses in profile transactions aggregate

---

packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts

When calling `profile.restore` with multiple wallets, the wallets are marked (as expected) as partially restored. Though there are some wallets that are not marked as fully restored when running `profile.sync` when wallet's coin is already synced. 
This PR ensures that the wallet is marked as fully restored when syncing with network.

fix: ensure wallet is marked as fully restored when coin is synced in `setCoin`

---

packages/platform-sdk-profiles/src/drivers/memory/index.ts
packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts
packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.test.ts

refactor(profiles): save changes only for restored profiles

---

packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
packages/platform-sdk-trx/src/services/transaction.ts

Under certain circumstances `wallet.data().get(WalletData.Balance)` is `"0"`, causing the balance method to return an invalid BigNumber instance which in turn breakes the calculation of converted balances.

fix(profiles): avoid return a BigNumber instance that is a number as balance

---

packages/platform-sdk-ada/src/services/signatory.ts
packages/platform-sdk-ark/src/services/signatory.ts
packages/platform-sdk-atom/src/services/signatory.ts
packages/platform-sdk-avax/src/services/signatory.ts
packages/platform-sdk-btc/src/services/signatory.ts
packages/platform-sdk-dot/src/services/signatory.ts
packages/platform-sdk-egld/src/services/signatory.ts
packages/platform-sdk-eos/src/services/signatory.ts
packages/platform-sdk-eth/src/services/signatory.ts
packages/platform-sdk-lsk/src/services/signatory.ts
packages/platform-sdk-luna/src/services/signatory.ts
packages/platform-sdk-nano/src/services/signatory.ts
packages/platform-sdk-neo/src/services/signatory.ts
packages/platform-sdk-sol/src/services/signatory.ts
packages/platform-sdk-trx/src/services/signatory.ts
packages/platform-sdk-xlm/src/services/signatory.ts
packages/platform-sdk-xrp/src/services/signatory.ts
packages/platform-sdk-zil/src/services/signatory.ts
packages/platform-sdk/src/signatories/abstract-signatory-service.ts
packages/platform-sdk/src/signatories/index.ts

Most coins will share the majority of these behaviours but there's a few exceptions. For transaction/message signing for example some coins use the address as an identifier but others use a public key so we can create some defaults but coins can overwrite them as they need.

refactor: introduce `AbstractSignatoryService`

---

packages/platform-sdk-profiles/src/contracts/contacts/contact-address.ts
packages/platform-sdk-profiles/src/drivers/memory/contacts/contact-address.test.ts
packages/platform-sdk-profiles/src/drivers/memory/contacts/contact-address.ts
packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-address-repository.test.ts
packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-address-repository.ts
packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.test.ts

Since contacts should not have more than one address for each individual network there is no need for the additional name.

refactor: remove `IContactAddress#name`

---

common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
packages/platform-sdk-ada/src/services/link.ts
packages/platform-sdk-ark/src/services/link.ts
packages/platform-sdk-atom/src/services/link.ts
packages/platform-sdk-avax/src/services/link.ts
packages/platform-sdk-btc/src/services/link.ts
packages/platform-sdk-dot/src/services/link.ts
packages/platform-sdk-egld/src/services/link.ts
packages/platform-sdk-eos/src/services/link.ts
packages/platform-sdk-eth/src/services/link.ts
packages/platform-sdk-lsk/src/services/link.ts
packages/platform-sdk-luna/src/services/link.ts
packages/platform-sdk-nano/src/services/link.ts
packages/platform-sdk-neo/src/services/link.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/__snapshots__/wallet.test.ts.snap
packages/platform-sdk-profiles/src/environment/__snapshots__/env.test.ts.snap
packages/platform-sdk-sol/src/services/link.ts
packages/platform-sdk-trx/src/services/link.ts
packages/platform-sdk-xlm/src/services/link.ts
packages/platform-sdk-xrp/src/services/link.ts
packages/platform-sdk-zil/src/services/link.ts
packages/platform-sdk/package.json
packages/platform-sdk/src/services/link.ts

Use string formatting instead of templates to reduce duplication even further.

refactor(sdk): further DRY the `LinkService`

---

packages/platform-sdk-support/src/bignumber.test.ts
packages/platform-sdk-support/src/bignumber.ts

Array#reduce is considered harmful when the underlying intent is simply to do a sum or a string concat.
https://betterprogramming.pub/think-again-before-you-use-array-reduce-28f785b5aea9

feat(support): add `BigNumber#sum` method

---

packages/platform-sdk-profiles/src/contracts/wallets/wallet.factory.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.test.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.ts

Allow an optional password argument to encrypt a BIP39 wallet, instead of keeping it as a separate method. This will later on be also applied to BIP44/49/84 once integrated into DW.

refactor(profiles): replace `fromMnemonicWithEncryption` with a `password` argument for `fromMnemonicWithBIP39`

---

.github/workflows/ci.yml

Hopefully prevents the annoying failures because of the local linking.

ci: install `rimraf` as a global dependency

---

packages/platform-sdk/src/coins/coin.test.ts
packages/platform-sdk/src/coins/coin.ts
packages/platform-sdk/src/coins/contracts.ts
packages/platform-sdk/src/ioc/service-provider.ts
packages/platform-sdk/src/services/big-number.service.ts
packages/platform-sdk/src/services/big-number.test.ts
packages/platform-sdk/src/services/index.ts

This service can be accessed through every coin instance like `coin.bigNumber().make(value)` and will remove the need for passing around the decimals as much as it is currently done.

feat(sdk): implement `BigNumberService`

---

packages/platform-sdk-json-rpc/src/helpers.ts
packages/platform-sdk-json-rpc/src/index.ts
packages/platform-sdk-json-rpc/src/methods/client.ts
packages/platform-sdk-json-rpc/src/methods/identity/address.ts
packages/platform-sdk-json-rpc/src/methods/identity/keys.ts
packages/platform-sdk-json-rpc/src/methods/identity/private-key.ts
packages/platform-sdk-json-rpc/src/methods/identity/public-key.ts
packages/platform-sdk-json-rpc/src/methods/identity/wif.ts
packages/platform-sdk-json-rpc/src/methods/message.ts
packages/platform-sdk-json-rpc/src/methods/transaction.ts
packages/platform-sdk-json-rpc/src/methods/wallet.ts

If not removed they will be sent to APIs and can result in errors if strict validation is used remotely.

fix(json-rpc): remove `coin` and `network` parameters after consuming them

---

packages/platform-sdk-btc-indexer/src/database.ts
packages/platform-sdk/src/coins/coin.ts

Implementation that considers error and stops if not a unique constraint violation

refactor(btc-indexer): only ignore error if unique constraint violation

---

packages/platform-sdk-btc-indexer/bin/meow.js
packages/platform-sdk-btc-indexer/prisma/migrations/20210608105900_pending_blocks/migration.sql
packages/platform-sdk-btc-indexer/prisma/schema.prisma
packages/platform-sdk-btc-indexer/src/client.ts
packages/platform-sdk-btc-indexer/src/database.ts
packages/platform-sdk-btc-indexer/src/helpers.ts
packages/platform-sdk-btc-indexer/src/index.ts
packages/platform-sdk/src/coins/coin-factory.test.ts

1. Downloaded blocks are stored in the database as pending blocks
2. All blocks between the `localHeight` and `remoteHeight` are downloaded and stored independently from the persistence into the `blocks` and `transactions` table
3. Every 30 seconds we process all pending blocks
The flow now is `download new blocks > store as pending > process pending every 30 seconds > delete processed blocks` which should make things more resilient against crashes because we don't need to re-download a bunch of blocks and we can also have better error handling because we have the data sitting in our database until we successfully process and persist it.
The potential overlap in processing caused by `setInterval` shouldn't be an issue because we `upsert` blocks which means we would be just updating an …

refactor(btc-indexer): store pending blocks in database

---

packages/platform-sdk-ada/src/services/transaction.ts
packages/platform-sdk-ark/src/services/transaction.ts
packages/platform-sdk-atom/src/services/transaction.ts
packages/platform-sdk-avax/src/services/transaction.ts
packages/platform-sdk-btc/src/services/transaction.ts
packages/platform-sdk-dot/src/services/transaction.ts
packages/platform-sdk-egld/src/services/transaction.ts
packages/platform-sdk-eos/src/services/transaction.ts
packages/platform-sdk-eth/src/services/transaction.ts
packages/platform-sdk-lsk/src/services/transaction.ts
packages/platform-sdk-luna/src/services/transaction.ts
packages/platform-sdk-nano/src/services/transaction.ts
packages/platform-sdk-neo/src/services/transaction.ts
packages/platform-sdk-profiles/src/contracts/wallets/wallet-transaction-service.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet-transaction-service.ts
packages/platform-sdk-sol/src/services/transaction.ts
packages/platform-sdk-trx/src/services/transaction.ts
packages/platform-sdk-xlm/src/services/transaction.ts
packages/platform-sdk-xrp/src/services/transaction.ts
packages/platform-sdk-zil/src/services/transaction.ts
packages/platform-sdk/src/services/transaction.contract.ts
packages/platform-sdk/src/services/transaction.service.ts

No longer needed because we now have the signatory setup which handles this much cleaner.

refactor(sdk): remove `TransactionOptions` in favour of `Signatory`

---

packages/platform-sdk-ark/src/services/transaction.test.ts
packages/platform-sdk-ark/src/services/transaction.ts
packages/platform-sdk-lsk/src/services/transaction.ts
packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet-transaction-service.ts
packages/platform-sdk/src/coins/coin.ts
packages/platform-sdk/src/services/signatory.contract.ts
packages/platform-sdk/src/services/signatory.service.ts
packages/platform-sdk/src/signatories/index.ts
packages/platform-sdk/src/signatories/signatory.test.ts
packages/platform-sdk/src/signatories/signatory.ts
packages/platform-sdk/src/signatories/signature.ts

`SignatureSignatory` was introduced to handle ledger signing but we now reworked that have the `LedgerSignatory` instead.

refactor(sdk): remove `SignatureSignatory` in favour of `LedgerSignatory`

---

jest.coverage.js
packages/platform-sdk-profiles/source/dto/transaction.test.ts
packages/platform-sdk-profiles/source/dto/transaction.ts
packages/platform-sdk-support/source/bignumber.ts

Ensures that the wrapped DTOs don't create different numbers and also fixes a few bugs with decimals not being persisted when using operations on a `BigNumber` instance.

fix(profiles): use `denominated` amount for conversion

---

packages/platform-sdk-intl/source/numeral.ts

This PR updates `Numeral` to allow for `undefined` locale since the wrapped Intl.NumberFormat doesn't require it either.

refactor(intl): make Numeral locale optional

---

packages/platform-sdk-ada/source/client.service.ts
packages/platform-sdk-ark/source/__snapshots__/ledger.service.test.ts.snap
packages/platform-sdk-ark/source/client.service.ts
packages/platform-sdk-ark/source/wallet.dto.test.ts
packages/platform-sdk-ark/source/wallet.dto.ts
packages/platform-sdk-atom/source/client.service.ts
packages/platform-sdk-avax/source/client.service.ts
packages/platform-sdk-btc/source/client.service.ts
packages/platform-sdk-dot/source/client.service.ts
packages/platform-sdk-egld/source/client.service.ts
packages/platform-sdk-eos/source/client.service.ts
packages/platform-sdk-eth/source/client.service.ts
packages/platform-sdk-json-rpc/bin/meow.js
packages/platform-sdk-json-rpc/source/index.ts
packages/platform-sdk-json-rpc/source/methods/business.ts
packages/platform-sdk-lsk/source/__snapshots__/ledger.service.test.ts.snap
packages/platform-sdk-lsk/source/client.service.ts
packages/platform-sdk-lsk/source/wallet.dto.test.ts
packages/platform-sdk-nano/source/client.service.ts
packages/platform-sdk-neo/source/client.service.ts
packages/platform-sdk-sol/source/client.service.ts
packages/platform-sdk-trx/source/client.service.ts
packages/platform-sdk-xlm/source/client.service.ts
packages/platform-sdk-xrp/source/client.service.ts
packages/platform-sdk-zil/source/client.service.ts
packages/platform-sdk/source/dto/wallet.ts
packages/platform-sdk/source/services/data-transfer-object.service.ts

Ensures consistency and that the `BigNumberService` is accessible when needed, for things like balances. Noticed this while working on the JSON-RPC which caused a bug with `toHuman()` on balances.

fix: create `WalletData` through `DataTransferObjectService`

---

packages/platform-sdk-ada/source/wallet.dto.test.ts
packages/platform-sdk-ada/source/wallet.dto.ts
packages/platform-sdk-ark/source/wallet.dto.test.ts
packages/platform-sdk-atom/source/wallet.dto.test.ts
packages/platform-sdk-atom/source/wallet.dto.ts
packages/platform-sdk-avax/source/wallet.dto.ts
packages/platform-sdk-btc/source/wallet.dto.test.ts
packages/platform-sdk-btc/source/wallet.dto.ts
packages/platform-sdk-dot/source/wallet.dto.ts
packages/platform-sdk-egld/source/wallet.dto.ts
packages/platform-sdk-eos/source/wallet.dto.test.ts
packages/platform-sdk-eos/source/wallet.dto.ts
packages/platform-sdk-eth/source/wallet.dto.test.ts
packages/platform-sdk-eth/source/wallet.dto.ts
packages/platform-sdk-lsk/source/wallet.dto.ts
packages/platform-sdk-neo/source/wallet.dto.test.ts
packages/platform-sdk-neo/source/wallet.dto.ts
packages/platform-sdk-profiles/source/serialiser.test.ts
packages/platform-sdk-profiles/source/serialiser.ts
packages/platform-sdk-profiles/source/wallet.ts
packages/platform-sdk-sol/source/wallet.dto.ts
packages/platform-sdk-trx/source/wallet.dto.test.ts
packages/platform-sdk-xlm/source/wallet.dto.test.ts
packages/platform-sdk-xlm/source/wallet.dto.ts
packages/platform-sdk-xrp/source/wallet.dto.test.ts
packages/platform-sdk-xrp/source/wallet.dto.ts
packages/platform-sdk-zil/source/wallet.dto.ts

Ensures that decimals are provided consistently to avoid unexpected values for the client.

fix: always use `BigNumberService` for `BigNumber` creation in DTOs

---

packages/platform-sdk-profiles/source/wallet-transaction.service.test.ts
packages/platform-sdk-profiles/source/wallet.contract.ts
packages/platform-sdk-profiles/source/wallet.factory.contract.ts
packages/platform-sdk-profiles/source/wif.ts
packages/platform-sdk-support/source/uri.test.ts
packages/platform-sdk-support/source/uri.ts
packages/platform-sdk/source/networks/network.test.ts
packages/platform-sdk/source/networks/network.ts

There are some occurrences in the Desktop Wallet where the networks coin name is concatenated with the network name, e.g. `` `${network.coin()} ${network.name()}` ``. The DW also uses some hardcoded display names. For `live` networks the network name is generally omitted, hence the check in the `displayName` method.

refactor(sdk): implement `Network#displayName`
