ArkEcosystem/platform-sdk

__tests__/clients/adapters/ark.test.ts, __tests__/clients/adapters/btc.test.ts, __tests__/clients/adapters/eth.test.ts, __tests__/crypto/adapters/btc.test.ts, __tests__/crypto/adapters/eth.test.ts, package.json, src/clients/adapters/ark.ts, src/clients/adapters/btc.ts, src/clients/adapters/eth.ts, src/clients/contracts.ts, src/clients/dtos/block.ts, src/clients/dtos/transaction.ts, src/clients/dtos/wallet.ts, src/clients/factory.ts, yarn.lock
Using devnet for tests at the moment and still missing DTOs but they need to be compared with some other networks before normalising the data.
=> feat: initial implementation of ARK client

__tests__/identities/adapters/__fixtures__/eth.ts, __tests__/identities/adapters/eth.test.ts, package.json, src/identities/adapters/ark.ts, src/identities/adapters/btc.ts, src/identities/adapters/eth.ts, yarn.lock
Missing quite a few methods due to certain things not being available in JS packages or not existing at all.
=> feat: identity generation for ETH

package.json, src/coins/btc/client.ts, src/coins/eth/client.ts, src/coins/eth/crypto.ts, yarn.lock
=> feat: basic client setup for ETH

__tests__/coins/ark/dto/peer.test.ts, __tests__/coins/lsk/dto/peer.test.ts, src/coins/ark/dto/peer.ts, src/coins/btc/dto/peer.ts, src/coins/contracts/client.ts, src/coins/eth/dto/peer.ts, src/coins/lsk/dto/peer.ts, src/coins/trx/dto/peer.ts
Only ARK and LSK for now because for others we won't be really using network peers.
=> feat: initial draft of normalised Peer DTO

README.md, __tests__/coins/ark/client.test.ts, src/coins/ark/client.ts, src/coins/btc/client.ts, src/coins/contracts/client.ts, src/coins/eth/client.ts, src/coins/lsk/client.ts, src/coins/trx/client.ts
The `getBridgechainsByBusiness` is way too specific to ARK to be included.
=> refactor: remove getBridgechainsByBusiness

packages/platform-sdk-xrp/src/services/transaction.ts
https://github.com/ArkEcosystem/platform-sdk/issues/68
=> fix(xrp): treat amounts as strings

packages/platform-sdk-ark/src/dto/wallet.ts, packages/platform-sdk-atom/src/dto/wallet.ts, packages/platform-sdk-btc/src/dto/wallet.ts, packages/platform-sdk-eos/src/dto/wallet.ts, packages/platform-sdk-eth/src/dto/wallet.ts, packages/platform-sdk-lsk/src/dto/wallet.ts, packages/platform-sdk-neo/src/dto/wallet.ts, packages/platform-sdk-trx/src/dto/wallet.ts, packages/platform-sdk-xmr/src/dto/wallet.ts, packages/platform-sdk-xrp/src/dto/wallet.ts, packages/platform-sdk/src/contracts/coins/data.ts
https://github.com/ArkEcosystem/platform-sdk/issues/66
=> feat: add `WalletData#getNonce` method

packages/platform-sdk-xrp/__tests__/services/client.test.ts, packages/platform-sdk-xrp/src/services/client.ts
https://github.com/ArkEcosystem/platform-sdk/issues/80
=> fix(xrp): only list payments when using `Client#getTransactions`

packages/platform-sdk-lsk/__tests__/__fixtures__/client/getTransaction-betanet.json, packages/platform-sdk-lsk/src/dto/transaction.ts
https://github.com/ArkEcosystem/platform-sdk/issues/77
=> fix(lsk): use testnet transaction structure

packages/platform-sdk-ark/src/dto/delegate.ts, packages/platform-sdk-atom/src/dto/delegate.ts, packages/platform-sdk-btc/src/dto/delegate.ts, packages/platform-sdk-eos/src/dto/delegate.ts, packages/platform-sdk-eth/src/dto/delegate.ts, packages/platform-sdk-lsk/src/dto/delegate.ts, packages/platform-sdk-neo/src/dto/delegate.ts, packages/platform-sdk-trx/src/dto/delegate.ts, packages/platform-sdk-xmr/src/dto/delegate.ts, packages/platform-sdk-xrp/src/dto/delegate.ts, packages/platform-sdk/src/contracts/coins/data.ts, packages/platform-sdk/src/dto/delegate.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/88
=> feat: add `DelegateData#getUsername` and `DelegateData#getRank`

packages/platform-sdk-ark/__tests__/__fixtures__/client/getVoters.json, packages/platform-sdk-ark/__tests__/__fixtures__/client/getVotes.json, packages/platform-sdk-ark/__tests__/services/client.test.ts, packages/platform-sdk-ark/__tests__/services/transaction.test.ts, packages/platform-sdk-ark/src/services/transaction.ts, packages/platform-sdk-atom/__tests__/services/transaction.test.ts, packages/platform-sdk-atom/src/services/client.ts, packages/platform-sdk-atom/src/services/transaction.ts, packages/platform-sdk-btc/src/services/client.ts, packages/platform-sdk-btc/src/services/transaction.ts, packages/platform-sdk-eos/src/services/client.ts, packages/platform-sdk-eos/src/services/transaction.ts, packages/platform-sdk-eth/src/services/client.ts, packages/platform-sdk-eth/src/services/transaction.ts, packages/platform-sdk-lsk/__tests__/services/transaction.test.ts, packages/platform-sdk-lsk/src/services/client.ts, packages/platform-sdk-lsk/src/services/transaction.ts, packages/platform-sdk-neo/src/services/client.ts, packages/platform-sdk-neo/src/services/transaction.ts, packages/platform-sdk-trx/__tests__/services/transaction.test.ts, packages/platform-sdk-trx/src/services/client.ts, packages/platform-sdk-trx/src/services/transaction.ts, packages/platform-sdk-xmr/src/services/client.ts, packages/platform-sdk-xmr/src/services/transaction.ts, packages/platform-sdk-xrp/src/services/client.ts, packages/platform-sdk-xrp/src/services/transaction.ts, packages/platform-sdk/src/contracts/coins/transaction.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/70
=> refactor: standardise the input for the `Transaction#create*` methods

packages/platform-sdk-ark/src/services/message.ts, packages/platform-sdk-atom/src/services/message.ts, packages/platform-sdk-btc/src/services/message.ts, packages/platform-sdk-eos/src/services/message.ts, packages/platform-sdk-eth/src/services/message.ts, packages/platform-sdk-lsk/src/services/message.ts, packages/platform-sdk-neo/src/services/message.ts, packages/platform-sdk-trx/src/services/message.ts, packages/platform-sdk-xmr/src/services/message.ts, packages/platform-sdk-xrp/src/services/message.ts, packages/platform-sdk/src/contracts/coins/message.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/108
=> refactor: add contract for `MessageService` input

packages/platform-sdk-ark/src/services/transaction.ts, packages/platform-sdk-atom/src/services/transaction.ts, packages/platform-sdk-btc/src/services/transaction.ts, packages/platform-sdk-eos/src/services/transaction.ts, packages/platform-sdk-eth/src/services/transaction.ts, packages/platform-sdk-lsk/src/services/transaction.ts, packages/platform-sdk-neo/src/services/transaction.ts, packages/platform-sdk-trx/src/services/transaction.ts, packages/platform-sdk-xmr/src/services/transaction.ts, packages/platform-sdk-xrp/src/services/transaction.ts, packages/platform-sdk/src/contracts/coins/identity.ts, packages/platform-sdk/src/contracts/coins/transaction.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/111
=> feat: add `options` for transaction signing

packages/platform-sdk-ark/__tests__/services/peer.test.ts, packages/platform-sdk-ark/src/services/peer.ts, packages/platform-sdk-atom/src/services/peer.ts, packages/platform-sdk-btc/src/services/peer.ts, packages/platform-sdk-eos/src/services/peer.ts, packages/platform-sdk-eth/src/services/peer.ts, packages/platform-sdk-lsk/src/services/peer.ts, packages/platform-sdk-neo/src/services/peer.ts, packages/platform-sdk-trx/src/services/peer.ts, packages/platform-sdk-xmr/src/services/peer.ts, packages/platform-sdk-xrp/src/services/peer.ts, packages/platform-sdk/src/contracts/coins/peer.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/120
=> refactor: turn `PeerService` fluent helpers into options

docs/manifest.md
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/125
=> docs: add manifest usage details

packages/platform-sdk-ark/src/services/identity.ts, packages/platform-sdk-atom/src/services/identity.ts, packages/platform-sdk-btc/src/services/identity.ts, packages/platform-sdk-eos/src/services/identity.ts, packages/platform-sdk-eth/src/services/identity.ts, packages/platform-sdk-lsk/src/services/identity.ts, packages/platform-sdk-neo/src/services/identity.ts, packages/platform-sdk-trx/src/services/identity.ts, packages/platform-sdk-xmr/src/services/identity.ts, packages/platform-sdk-xrp/src/services/identity.ts, packages/platform-sdk/src/exceptions.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/124
=> fix: add missing exceptions for `IdentityService`

packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ada/src/services/link.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-ark/src/services/link.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-atom/src/services/link.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-btc/src/services/link.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eos/src/services/link.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-eth/src/services/link.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-lsk/src/services/link.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-neo/src/services/link.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-trx/src/services/link.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xmr/src/services/link.ts, packages/platform-sdk-xrp/src/manifest.ts, packages/platform-sdk-xrp/src/services/link.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/139
=> refactor: include basic network information in `manifest`

packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-atom/src/services/identity.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-eth/src/services/identity.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xrp/src/manifest.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/162
=> chore: add derivation path to manifests

packages/platform-sdk-ark/__tests__/factory.test.ts, packages/platform-sdk-atom/__tests__/factory.test.ts, packages/platform-sdk-btc/__tests__/factory.test.ts, packages/platform-sdk-eth/__tests__/factory.test.ts, packages/platform-sdk-lsk/__tests__/factory.test.ts, packages/platform-sdk-neo/__tests__/factory.test.ts, packages/platform-sdk-xrp/__tests__/factory.test.ts, packages/platform-sdk/src/contracts/coins/factory.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/147
=> test: add unit tests for `Factory` classes

packages/platform-sdk/src/contracts/coins/factory.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/176
=> refactor: force network name to be live, demo or test

packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-atom/src/services/identity/address.ts, packages/platform-sdk-atom/src/services/identity/keys.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-eth/src/services/identity/utils.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-neo/src/services/identity/utils.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xrp/src/manifest.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/175
=> chore: add `crypto` key to manifest to hold BIP values

docs/coins/index.md, docs/coins/services/ledger.md, packages/platform-sdk-ark/src/services/ledger.ts, packages/platform-sdk-atom/src/services/ledger.ts, packages/platform-sdk-btc/src/services/ledger.ts, packages/platform-sdk-eos/src/services/ledger.ts, packages/platform-sdk-eth/src/services/ledger.ts, packages/platform-sdk-lsk/src/services/ledger.ts, packages/platform-sdk-neo/src/services/ledger.ts, packages/platform-sdk-trx/src/services/ledger.ts, packages/platform-sdk-xmr/src/services/ledger.ts, packages/platform-sdk-xrp/src/services/ledger.ts, packages/platform-sdk/src/contracts/coins/ledger.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/130
=> docs: add `LedgerService` documentation

packages/platform-sdk-atom/src/services/message.ts, packages/platform-sdk-atom/src/utils/crypto.ts, packages/platform-sdk-atom/src/utils/hash.ts, packages/platform-sdk-eth/src/services/identity/address.ts, packages/platform-sdk-eth/src/services/identity/keys.ts, packages/platform-sdk-eth/src/services/identity/public-key.ts, packages/platform-sdk-eth/src/services/transaction.ts, packages/platform-sdk-xlm/src/services/message.ts, packages/platform-sdk-xrp/src/services/message.ts, packages/platform-sdk/src/utils/buffoon.ts, packages/platform-sdk/src/utils/index.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/215
=> refactor: group repeated `Buffer` behaviours into a class

packages/platform-sdk-ark/__tests__/dto/transaction.test.ts, packages/platform-sdk-ark/src/dto/transaction.ts, packages/platform-sdk-atom/__tests__/dto/transaction.test.ts, packages/platform-sdk-atom/__tests__/services/client.test.ts, packages/platform-sdk-atom/src/dto/transaction.ts, packages/platform-sdk-btc/__tests__/dto/transaction.test.ts, packages/platform-sdk-btc/__tests__/services/client.test.ts, packages/platform-sdk-btc/src/dto/transaction.ts, packages/platform-sdk-eos/src/dto/transaction.ts, packages/platform-sdk-eth/__tests__/dto/transaction.test.ts, packages/platform-sdk-eth/__tests__/services/client.test.ts, packages/platform-sdk-eth/src/dto/transaction.ts, packages/platform-sdk-lsk/__tests__/dto/transaction.test.ts, packages/platform-sdk-lsk/src/dto/transaction.ts, packages/platform-sdk-neo/__tests__/dto/transaction.test.ts, packages/platform-sdk-neo/__tests__/services/client.test.ts, packages/platform-sdk-neo/src/dto/transaction.ts, packages/platform-sdk-trx/src/dto/transaction.ts, packages/platform-sdk-xlm/__tests__/services/client.test.ts, packages/platform-sdk-xlm/src/dto/transaction.ts, packages/platform-sdk-xmr/src/dto/transaction.ts, packages/platform-sdk-xrp/__tests__/dto/transaction.test.ts, packages/platform-sdk-xrp/__tests__/services/client.test.ts, packages/platform-sdk-xrp/src/dto/transaction.ts, packages/platform-sdk/src/contracts/coins/data.ts, packages/platform-sdk/src/dto/transaction.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/218
=> feat: implement `TransactionData#asset`

packages/platform-sdk-ark/__tests__/services/transaction.test.ts, packages/platform-sdk-atom/__tests__/services/transaction.test.ts, packages/platform-sdk-trx/__tests__/services/transaction.test.ts, packages/platform-sdk/src/contracts/coins/transaction.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/233
=> fix: always treat `fee` and `amount` as `string`

packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-atom/__tests__/services/transaction.test.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-xlm/src/manifest.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xrp/src/manifest.ts, packages/platform-sdk/src/coins/factory.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/244
=> chore: add currency symbols to manifest

packages/platform-sdk/src/coins/manifest.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/252
=> feat(sdk): implement `Manifest`

docs/coins/manifest.md, packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ark/src/index.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-atom/src/index.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-btc/src/index.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-coincap/src/index.ts, packages/platform-sdk-coingecko/src/index.ts, packages/platform-sdk-cryptocompare/src/index.ts, packages/platform-sdk-eos/src/index.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eth/src/index.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-lsk/src/index.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-neo/src/index.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-trx/src/index.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-xlm/src/index.ts, packages/platform-sdk-xlm/src/manifest.ts, packages/platform-sdk-xmr/src/index.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xrp/src/index.ts, packages/platform-sdk-xrp/src/manifest.ts, packages/platform-sdk/src/coins/factory.ts, packages/platform-sdk/src/coins/guard.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/253
=> feat(sdk): implement `Guard` to protect against bad method calls

packages/platform-sdk-ark/__tests__/services/ledger.test.ts, packages/platform-sdk-ark/src/schema.ts, packages/platform-sdk-ark/src/services/ledger.ts, packages/platform-sdk-atom/src/schema.ts, packages/platform-sdk-atom/src/services/ledger.ts, packages/platform-sdk-btc/src/services/ledger.ts, packages/platform-sdk-eos/src/services/ledger.ts, packages/platform-sdk-eth/__tests__/services/ledger.test.ts, packages/platform-sdk-eth/src/schema.ts, packages/platform-sdk-eth/src/services/ledger.ts, packages/platform-sdk-lsk/__tests__/services/ledger.test.ts, packages/platform-sdk-lsk/src/schema.ts, packages/platform-sdk-lsk/src/services/ledger.ts, packages/platform-sdk-neo/src/services/ledger.ts, packages/platform-sdk-trx/__tests__/services/ledger.test.ts, packages/platform-sdk-trx/src/schema.ts, packages/platform-sdk-trx/src/services/ledger.ts, packages/platform-sdk-xlm/__tests__/services/ledger.test.ts, packages/platform-sdk-xlm/src/schema.ts, packages/platform-sdk-xlm/src/services/ledger.ts, packages/platform-sdk-xmr/src/services/ledger.ts, packages/platform-sdk-xrp/__tests__/services/ledger.test.ts, packages/platform-sdk-xrp/src/schema.ts, packages/platform-sdk-xrp/src/services/ledger.ts, packages/platform-sdk/src/contracts/coins/ledger.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/246
=> feat: implement `LedgerService#connect` and `LedgerService#disconnect`

packages/platform-sdk-ark/src/services/identity/address.ts, packages/platform-sdk-ark/src/services/transaction.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/272
=> feat(ark): look up nonce if none is provided

.github/workflows/test.yml, packages/platform-sdk/__tests__/coins/services/uri.test.ts, packages/platform-sdk/src/coins/index.ts, packages/platform-sdk/src/coins/services/index.ts, packages/platform-sdk/src/coins/services/uri.ts, packages/platform-sdk/src/contracts/coins/index.ts, packages/platform-sdk/src/contracts/coins/uri.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/295
This is an initial implementation and might be turned into an abstract later and require each coin to extend the abstract and implement their own validation logic of the received data.
=> feat(sdk): implement URIService

packages/platform-sdk-profiles/__tests__/wallets/wallet-repository.test.ts, packages/platform-sdk-profiles/__tests__/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet-repository.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/324
=> fix(profiles): prevent duplicate wallets per profile

packages/platform-sdk-intl/__tests__/numeral.test.ts, packages/platform-sdk-intl/src/index.ts, packages/platform-sdk-intl/src/number.ts, packages/platform-sdk-intl/src/numeral.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/310
=> feat(intl): implement `Numeral` for number formatting

packages/platform-sdk-profiles/src/wallets/wallet.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/334
=> feat(profiles): implement `Wallet#transactions/sentTransactions/receivedTransactions`

packages/platform-sdk-ark/src/services/client.ts, packages/platform-sdk-atom/src/services/client.ts, packages/platform-sdk-btc/src/services/client.ts, packages/platform-sdk-eos/src/services/client.ts, packages/platform-sdk-eth/__tests__/services/client.test.ts, packages/platform-sdk-eth/src/services/client.ts, packages/platform-sdk-lsk/src/services/client.ts, packages/platform-sdk-neo/src/services/client.ts, packages/platform-sdk-trx/src/services/client.ts, packages/platform-sdk-xlm/src/services/client.ts, packages/platform-sdk-xmr/src/services/client.ts, packages/platform-sdk-xrp/src/services/client.ts, packages/platform-sdk/src/contracts/coins/client.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/346
=> feat(sdk): add `ClientTransactionsInput` and `ClientWalletsInput` contracts

packages/platform-sdk-support/__tests__/bignumber.test.ts, packages/platform-sdk-support/src/bignumber.ts
Accept decimal point parameter on `BigNumber.toFixed()` method
=> refactor(support): add `decimals` parameter to `BigNumber#toFixed`

docs/coins/services/transaction.md, packages/platform-sdk-ark/__tests__/services/peer.test.ts, packages/platform-sdk-ark/src/services/peer.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/294
=> fix(ark): handle connection attempt to peer of a different network

docs/EXAMPLES.md, packages/platform-sdk-profiles/__tests__/env.test.ts, packages/platform-sdk-profiles/__tests__/profile.test.ts, packages/platform-sdk-profiles/__tests__/repositories/notification-repository.test.ts, packages/platform-sdk-profiles/src/contracts.ts, packages/platform-sdk-profiles/src/env.ts, packages/platform-sdk-profiles/src/profile.ts, packages/platform-sdk-profiles/src/repositories/notification-repository.ts, packages/platform-sdk-profiles/src/repositories/profile-repository.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/435
=> feat(profiles): implement notifications

packages/platform-sdk-profiles/src/profile.ts, packages/platform-sdk-profiles/src/wallet.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/451
=> feat(profiles): implement `Profile#balance`

packages/platform-sdk-profiles/src/wallet.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/453
=> feat(profiles): implement `Wallet#alias`

packages/platform-sdk-ada/src/manifest.ts, packages/platform-sdk-ark/src/manifest.ts, packages/platform-sdk-atom/src/manifest.ts, packages/platform-sdk-btc/src/manifest.ts, packages/platform-sdk-eos/src/manifest.ts, packages/platform-sdk-eth/src/manifest.ts, packages/platform-sdk-lsk/src/manifest.ts, packages/platform-sdk-neo/src/manifest.ts, packages/platform-sdk-trx/src/manifest.ts, packages/platform-sdk-xlm/src/manifest.ts, packages/platform-sdk-xmr/src/manifest.ts, packages/platform-sdk-xrp/src/manifest.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/448
=> chore: expose voting support through manifest

packages/platform-sdk-profiles/src/wallet.models.ts, packages/platform-sdk-profiles/src/wallet.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/464
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/463
=> feat(profiles): implement wallet flags

packages/platform-sdk-profiles/__tests__/repositories/wallet-repository.test.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/465
=> feat(profiles): implement `WalletRepository#allByCoin`

docs/examples.md
=> chore: update examples.md

packages/platform-sdk-profiles/src/wallet.ts, packages/platform-sdk/src/contracts/coins/http.ts, packages/platform-sdk/src/http/request.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/507
=> feat(sdk): implement `Request#withCacheStore`

packages/platform-sdk-profiles/src/wallet.ts
Resolves https://github.com/ArkEcosystem/platform-sdk/issues/589
=> fix(profiles): restore wallet data and public key on sync error

packages/platform-sdk-profiles/src/index.ts
=> chore(profiles): export contact address types

packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts, packages/platform-sdk-profiles/src/repositories/profile-repository.ts
=> feat(profiles): implement `ProfileRepository#count`

packages/platform-sdk-profiles/src/contact.ts
=> feat(profiles): implement `Contact#avatar`

docs/examples.md, packages/platform-sdk-ark/src/services/client.test.ts, packages/platform-sdk-ark/src/services/client.ts, packages/platform-sdk-atom/src/services/client.test.ts, packages/platform-sdk-atom/src/services/client.ts, packages/platform-sdk-btc/src/services/client.ts, packages/platform-sdk-eos/src/services/client.ts, packages/platform-sdk-eth/src/services/client.test.ts, packages/platform-sdk-eth/src/services/client.ts, packages/platform-sdk-lsk/src/services/client.test.ts, packages/platform-sdk-lsk/src/services/client.ts, packages/platform-sdk-neo/src/services/client.test.ts, packages/platform-sdk-neo/src/services/client.ts, packages/platform-sdk-profiles/src/aggregates/transaction-aggregate.ts, packages/platform-sdk-profiles/src/wallet.ts, packages/platform-sdk-trx/src/services/client.ts, packages/platform-sdk-xlm/src/services/client.test.ts, packages/platform-sdk-xlm/src/services/client.ts, packages/platform-sdk-xmr/src/services/client.ts, packages/platform-sdk-xrp/src/services/client.test.ts, packages/platform-sdk-xrp/src/services/client.ts, packages/platform-sdk/src/coins/collections/paginator.ts, packages/platform-sdk/src/coins/collections/transactions.ts, packages/platform-sdk/src/coins/collections/wallets.ts, packages/platform-sdk/src/coins/index.ts, packages/platform-sdk/src/contracts/coins/client.ts, packages/platform-sdk/src/helpers.ts
> Resolves https://github.com/ArkEcosystem/platform-sdk/issues/615
=> feat(sdk): implement collection paginator

packages/platform-sdk-profiles/src/profiles/profile.models.ts
Renames the `AutomaticLogoffPeriod` profile setting to `AutomaticSignOutPeriod` to be more in line with the terminology used in the DW.
=> chore: rename `AutomaticLogoffPeriod` to `AutomaticSignOutPeriod`

packages/platform-sdk-ark/src/services/link.ts, packages/platform-sdk-profiles/src/dto/transaction.test.ts
Fixes the ARK block and transaction explorer links.
=> fix: ark explorer links

packages/platform-sdk-profiles/src/environment/container.models.ts, packages/platform-sdk-profiles/src/environment/env.ts, packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.test.ts, packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts, packages/platform-sdk-profiles/src/profiles/profile.models.ts, packages/platform-sdk-profiles/src/profiles/profile.test.ts, packages/platform-sdk-profiles/src/profiles/profile.ts, packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
https://app.clickup.com/t/7jm2fb
=> feat(profiles): sync exchanges rates globally instead of per wallet

packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.test.ts, packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts
=> feat(profiles): implement `ExchangeRateService#syncCoinByProfile`

packages/platform-sdk-profiles/src/repositories/wallet-repository.test.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts, packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
Implement `WalletRepository#update`.
=> feat(profiles): implement `WalletRepository#update`

packages/platform-sdk-profiles/src/profiles/profile.models.ts
Adds the `DashboardConfiguration` and `NewsFilters` settings to the `ProfileSettings` enum.
=> chore(profiles): adds some ui profile settings

packages/platform-sdk-profiles/src/dto/transaction.ts
Adds a helper method to get the converted transaction amount.
=> feat(profiles): implement TransactionData#convertedAmount

packages/platform-sdk-ark/src/dto/wallet.ts, packages/platform-sdk-atom/src/dto/wallet.ts, packages/platform-sdk-btc/src/dto/wallet.ts, packages/platform-sdk-eos/src/dto/wallet.ts, packages/platform-sdk-eth/src/dto/wallet.ts, packages/platform-sdk-lsk/src/dto/wallet.ts, packages/platform-sdk-neo/src/dto/wallet.ts, packages/platform-sdk-trx/src/dto/wallet.ts, packages/platform-sdk-xlm/src/dto/wallet.ts, packages/platform-sdk-xmr/src/dto/wallet.ts, packages/platform-sdk-xrp/src/dto/wallet.ts, packages/platform-sdk/src/contracts/coins/data.ts, packages/platform-sdk/src/contracts/coins/entity.ts, packages/platform-sdk/src/contracts/coins/index.ts, packages/platform-sdk/src/dto/wallet.ts
=> feat: implement `WalletData#entities`

packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts, packages/platform-sdk/src/contracts/coins/data.ts
=> feat(profiles): implement `ReadWriteWallet#username`

packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
=> feat(profiles): implement `ReadWriteWallet#entities`

packages/platform-sdk-ark/src/services/helpers.ts, packages/platform-sdk-ark/src/services/identity/index.ts, packages/platform-sdk-ark/src/services/transaction.ts
=> chore: re-apply ARK configurations before every crypto method call

packages/platform-sdk-lsk/src/dto/wallet.ts
Also handle delegate data in the `WalletData` class.
=> refactor(lsk): handle delegate format in WalletData

packages/platform-sdk-ark/src/dto/transaction.ts
=> fix(ark): entity action check

packages/platform-sdk-profiles/src/profiles/aggregates/wallet-aggregate.ts
=> fix(profiles): stop division by zero in balance calculation

packages/platform-sdk-ark/src/networks/ark/devnet.json, packages/platform-sdk-profiles/test/fixtures/network.json
According to the node configuration.
=> fix(ark): update slip44 version of devnet

packages/platform-sdk-lsk/src/dto/transaction.test.ts, packages/platform-sdk-lsk/src/dto/transaction.ts
=> fix(lsk): use `senderId` instead of `senderPublicKey`

packages/platform-sdk-ark/src/dto/transaction.ts, packages/platform-sdk-atom/src/dto/transaction.ts, packages/platform-sdk-btc/src/dto/transaction.ts, packages/platform-sdk-eos/src/dto/transaction.ts, packages/platform-sdk-eth/src/dto/transaction.ts, packages/platform-sdk-lsk/src/dto/transaction.ts, packages/platform-sdk-neo/src/dto/transaction.ts, packages/platform-sdk-profiles/src/dto/transaction.ts, packages/platform-sdk-trx/src/dto/transaction.ts, packages/platform-sdk-xlm/src/dto/transaction.ts, packages/platform-sdk-xmr/src/dto/transaction.ts, packages/platform-sdk-xrp/src/dto/transaction.ts, packages/platform-sdk/src/contracts/coins/data.ts, packages/platform-sdk/src/dto/transaction.ts
Implements a `isVoteCombination()` method.
=> feat(sdk): implement `TransactionData#isVoteCombination`

packages/platform-sdk-profiles/src/enums.ts
=> fix(profiles): update entity type enums to reflect AIP36

packages/platform-sdk/src/dto/transaction.ts
Reorders the types in the `#types` object so that specialized transaction types are returned over the general types.
=> fix(sdk): return specialized entity types with over general type

packages/platform-sdk-profiles/src/repositories/wallet-repository.test.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Implements the `WalletRepository#findByAlias` method.
=> feat: implement `WalletRepository#findByAlias`

packages/platform-sdk-lsk/src/dto/transaction.ts
Fixes: https://app.clickup.com/t/90vr56
=> fix(lsk): confirm lisk transactions greater than or equal to 101 confirmations

packages/platform-sdk-profiles/src/profiles/aggregates/registration-aggregate.ts
Prevent throwing an error if the wallet is not synced when checking if it is a delegate in registrations aggregate.
=> fix(profiles): check wallet is synced and delegate in aggregation

packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
=> fix: add `ReadWriteWallet#secondPublicKey`

packages/platform-sdk-ark/src/services/transaction.test.ts, packages/platform-sdk-ark/src/services/transaction.ts, packages/platform-sdk/src/contracts/coins/transaction.ts
Changes to sign transactions with Ledger.
=> feat(ark): compute transaction id with custom signature

packages/platform-sdk-ark/src/services/client.ts, packages/platform-sdk-ark/src/services/fee.ts
=> feat(ark): support for custom peers

packages/platform-sdk-profiles/src/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
https://app.clickup.com/t/a0xmbw
=> fix: normalise wallet balance before converting it

packages/platform-sdk-profiles/src/dto/transaction.ts
This potentially needs further adjusting to handle fiat and crypto.
=> fix(profiles): divide transaction total before converting it

packages/platform-sdk-support/src/uri.test.ts, packages/platform-sdk-support/src/uri.ts
https://app.clickup.com/t/a6unrf
=> feat(support): AIP13 & AIP26 compatibility

packages/platform-sdk-profiles/src/environment/env.test.ts, packages/platform-sdk-profiles/src/profiles/profile.models.ts, packages/platform-sdk-profiles/src/profiles/profile.test.ts, packages/platform-sdk-profiles/src/profiles/profile.ts
Add setting for development network usage
=> feat(profiles): add development network setting

packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts, packages/platform-sdk-profiles/src/repositories/profile-repository.ts
Iimplement the `ProfileRepository#findByName` helper method.
=> feat(profiles): implement `ProfileRepository#findByName`

packages/platform-sdk-profiles/src/environment/env.test.ts, packages/platform-sdk-profiles/src/environment/env.ts, packages/platform-sdk-profiles/src/environment/migrator.test.ts, packages/platform-sdk-profiles/src/environment/migrator.ts, packages/platform-sdk-profiles/test/fixtures/env-storage-corrupted.json, packages/platform-sdk-support/src/validator.ts
Depends on https://github.com/ArkEcosystem/platform-sdk/pull/856 as the `usedCoinsWithNetworks` method is now obsolete and coverage is unecessary.
=> test: add coverage for `src/environment`

packages/platform-sdk-profiles/src/profiles/profile.test.ts, packages/platform-sdk-profiles/src/profiles/profile.ts
=> test(profiles): add coverage for `src/profiles`

packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts
=> test(profiles): add remaining coverage for `profile-repository`

packages/platform-sdk-profiles/src/index.ts
=> chore(profiles): export `Migrator`

packages/platform-sdk-profiles/src/environment/env.test.ts, packages/platform-sdk-profiles/src/environment/env.ts
=> feat(profiles): flush `env` container

packages/platform-sdk-profiles/src/profiles/aggregates/transaction-aggregate.test.ts, packages/platform-sdk-profiles/src/profiles/aggregates/transaction-aggregate.ts
https://app.clickup.com/t/c4zdzu
=> refactor(profiles): flush only the aggregate transaction method

packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.test.ts, packages/platform-sdk-profiles/src/environment/services/exchange-rate-service.ts
=> fix(profiles): prevent null entries in `ExchangeRateService#restore`

packages/platform-sdk-profiles/src/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
https://app.clickup.com/t/d51287
=> fix(profiles): store flags when dumping wallet

packages/platform-sdk-profiles/src/repositories/wallet-repository.test.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts, packages/platform-sdk-profiles/src/wallets/wallet.factory.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.factory.ts, packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
https://app.clickup.com/t/d92cmy
=> refactor(profiles): define `LedgerIndex` as `WalletData`

packages/platform-sdk-ark/src/services/fee.ts
The fees should be strings according to the `TransactionFee` contract.
https://github.com/ArkEcosystem/platform-sdk/blob/07248bfb259f9d53971161eb90e79ca978d8a970/packages/platform-sdk/src/contracts/coins/fee.ts#L1-L6
=> refactor(ark): return strings in fee transform method

packages/platform-sdk-ark/src/networks/ark/devnet.ts, packages/platform-sdk-ark/src/networks/ark/mainnet.ts, packages/platform-sdk-ark/src/networks/compendia/mainnet.ts
=> chore(ark): add `dynamicFees` property to network configs

packages/platform-sdk-ark/src/services/transaction.test.ts, packages/platform-sdk-ark/src/services/transaction.ts, packages/platform-sdk/src/contracts/coins/transaction.ts
Add option on the transfer input to sign with expiration.
=> feat(ark): sign transfer with custom expiration

packages/platform-sdk-profiles/src/environment/services/fee-service.ts
=> chore: fix syncFees error message

packages/platform-sdk-ark/src/services/client.ts
https://app.clickup.com/t/e33qey
=> fix(ark): only use page, limit, orderBy as searchParams in v2 requests

packages/platform-sdk-avax/README.md
Update AVAX Readme Title.
```diff
- ARK Platform SDK - ARK
+ ARK Platform SDK - Avalanche
```
=> docs(avax): update readme title

packages/platform-sdk-profiles/src/wallets/wallet.models.ts
=> fix(profiles): expose `ReadWriteWallet#transactionTypes` method from wallet model

packages/platform-sdk-profiles/src/profiles/profile.models.ts
https://app.clickup.com/t/7gr7wk
=> feat(profiles): add `ProfileSetting.ErrorReporting`

packages/platform-sdk-profiles/src/wallets/wallet.models.ts, packages/platform-sdk-profiles/src/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/wallets/wallet.ts
https://app.clickup.com/t/et4waz
=> feat(profiles): implement `ReadWriteWallet#displayName`

packages/platform-sdk-profiles/src/profiles/profile.models.ts
https://app.clickup.com/t/e0x7j6
=> chore(profiles): add `ProfileSetting.DashboardTransactionHistory`

packages/platform-sdk-profiles/src/profiles/profile.models.ts, packages/platform-sdk-profiles/test/fixtures/network.json
Adds the `DoNotShowAdvancedModeDisclaimer` profile setting.
=> chore(profiles): add `ProfileSetting.DoNotShowAdvancedModeDisclaimer`

packages/platform-sdk-intl/src/currency.test.ts, packages/platform-sdk-intl/src/currency.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
The value returned by `Currency#fromString` called with an empty or zero as input currently looks like:
```ts
Currency.fromString("")
// => { display: "", value: "0000000" }
Currency.fromString("0")
// => { display: "0", value: "00000000" }
```
=> refactor(intl): append trailing zeros only if value is truthy

packages/platform-sdk-profiles/src/wallets/wallet.models.ts
=> fix(profiles): expose `ReadWriteWallet#wif` and `ReadWriteWallet#usesWIF` methods

packages/platform-sdk-profiles/src/profiles/profile.models.ts, packages/platform-sdk-profiles/src/profiles/profile.test.ts, packages/platform-sdk-profiles/src/profiles/profile.ts, packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts, packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
https://app.clickup.com/t/fx0z70
=> refactor(profiles): remove `excludeWalletsWithoutName` export setting

packages/platform-sdk-json-rpc/package.json, packages/platform-sdk-json-rpc/src/helpers.ts, packages/platform-sdk-json-rpc/src/index.ts, packages/platform-sdk-json-rpc/src/methods/client.ts, packages/platform-sdk-json-rpc/src/methods/wallet.ts
Makes it easier to generate wallets for languages that have no proper BIP39 libraries.
=> feat(json-rpc): implement wallet generation

packages/platform-sdk-profiles/src/wallets/wallet.ts
=> fix(profiles): include bip38 data in `ReadWriteWallet#toObject`

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-profiles/package.json, packages/platform-sdk-profiles/src/environment/storage/conf.test.ts, packages/platform-sdk-profiles/src/environment/storage/conf.ts, packages/platform-sdk-profiles/src/environment/storage/factory.ts
Uses https://github.com/sindresorhus/conf to store the environment dump in the system configuration path.
=> feat(profiles): implement storage that uses system configuration path

packages/platform-sdk-ark/src/services/client.ts
https://app.clickup.com/t/g71ucb
=> fix(ark): handle different broadcast response error types

packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
https://app.clickup.com/t/gf6qk2
=> refactor(profiles): implement `ReadWriteWallet#setWif`

packages/platform-sdk-profiles/src/contracts/repositories/wallet-repository.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts
https://app.clickup.com/t/gv8e6b
=> refactor(profiles): accept locale as argument in `WalletRepository#generate`

packages/platform-sdk-profiles/src/contracts/repositories/wallet-repository.ts
=> fix: expose locale as a parameter in wallet generation

packages/platform-sdk-btc-indexer/src/database.ts, packages/platform-sdk-profiles/src/helpers/password.ts
=> feat:(btc) aggregate transaction amount

packages/platform-sdk-cli/src/commands/create-wallet.ts, packages/platform-sdk-cli/src/commands/import-ledger-wallet.ts, packages/platform-sdk-profiles/src/contracts/profiles/profile.ts, packages/platform-sdk-profiles/src/contracts/repositories/wallet-repository.ts, packages/platform-sdk-profiles/src/contracts/wallets/wallet.factory.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/registration-aggregate.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/transaction-aggregate.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/wallet-aggregate.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/portfolio.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.test.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.test.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts, packages/platform-sdk-profiles/src/drivers/memory/services/exchange-rate-service.test.ts, packages/platform-sdk-profiles/src/drivers/memory/services/wallet-service.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts, packages/platform-sdk-profiles/src/dto/transaction.test.ts, packages/platform-sdk-profiles/src/environment/env.test.ts, packages/platform-sdk-profiles/test/helpers.ts
https://app.clickup.com/t/hh7w3n
=> refactor(profiles): remove import methods from `IWalletRepository`

packages/platform-sdk-profiles/src/contracts/wallets/wallet.gate.ts, packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.gate.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.gate.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
https://app.clickup.com/t/hh7x1b
=> refactor(profiles): extract ability methods into `IWalletGate`

packages/platform-sdk-cli/src/commands/access-wallet.ts, packages/platform-sdk-profiles/src/contracts/wallets/wallet.synchroniser.ts, packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts, packages/platform-sdk-profiles/src/drivers/memory/services/wallet-service.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.mutator.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.synchroniser.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
https://app.clickup.com/t/h37q4q
> Depends on https://github.com/ArkEcosystem/platform-sdk/pull/1335/
=> refactor(profiles): extract synchronisation methods into `IWalletSynchroniser`

packages/platform-sdk-btc-server/src/index.ts
=> fix(btc-server): accommodate endpoint to new db structure

packages/platform-sdk-profiles/src/contracts/wallets/wallet-transaction-service.ts
=> fix:(profiles) adjust param types in `ITransactionService` sign methods

packages/platform-sdk-profiles/src/contracts/wallets/wallet.enum.ts, packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
https://app.clickup.com/t/hz5v6a
=> refactor(profiles): store import method on wallet

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-egld/package.json, packages/platform-sdk-egld/src/services/transaction.ts, packages/platform-sdk-eth/package.json, packages/platform-sdk-eth/src/services/transaction.ts
=> chore: update coin libs

packages/platform-sdk-btc-indexer/src/database.ts
=> fix(btc-indexer): store tx id instead of hash

packages/platform-sdk-ark/src/services/transaction.ts
https://app.clickup.com/t/jf3g0u
=> refactor(ark): estimate transaction expiration if none is specified

packages/platform-sdk-trx/package.json, packages/platform-sdk-trx/src/dto/transaction.ts, packages/platform-sdk-trx/src/networks/trx/mainnet.ts, packages/platform-sdk-trx/src/services/client.test.ts, packages/platform-sdk-trx/src/services/client.ts, packages/platform-sdk-trx/test/fixtures/client/transactions.json, packages/platform-sdk-trx/test/helpers.ts
https://app.clickup.com/t/jh6a47
=> refactor(tron): use standard API to list transactions

packages/platform-sdk-profiles/src/contracts/profiles/services/password.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.encrypter.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/services/password.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/services/password.ts
=> feat(profiles): implement `IPasswordManager#forget`

packages/platform-sdk-ark/src/services/transaction.test.ts, packages/platform-sdk-ark/src/services/transaction.ts
=> fix(ark): use of network expiration 

packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.ts
=> fix(profiles): await profile restore

packages/platform-sdk-zil-indexer/README.md
Update ZIL Indexer readme banner link.
=> chore(zil-indexer): update banner link

packages/platform-sdk-ada/src/dto/wallet.test.ts, packages/platform-sdk-ada/src/dto/wallet.ts, packages/platform-sdk-trx/src/services/client.test.ts
=> fix(ada): correct balances

packages/platform-sdk-nano/src/services/message.test.ts, packages/platform-sdk-nano/src/services/message.ts
Need to figure out how to verify the message.
=> feat(nano): implement `MessageService`

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-nano/package.json, packages/platform-sdk-nano/src/networks/nano/mainnet.ts, packages/platform-sdk-nano/src/networks/nano/testnet.ts, packages/platform-sdk-nano/src/services/client.test.ts, packages/platform-sdk-nano/src/services/message.test.ts, packages/platform-sdk-nano/src/services/message.ts
- Use https://github.com/paulmillr/noble-ed25519 for signing and verification
- Replaces https://github.com/numsu/nanocurrency-web-js/blob/master/lib/ed25519.ts
=> feat(nano): implement `MessageService#verify`

examples/src/examples/transfer-trx.ts, packages/platform-sdk-trx/src/dto/transaction.ts, packages/platform-sdk-trx/src/services/transaction.ts
=> fix(trx): memo parsing and inclusion

packages/platform-sdk-profiles/src/environment/env.models.ts, packages/platform-sdk-profiles/src/environment/env.test.ts, packages/platform-sdk-profiles/src/environment/env.ts
=> refactor(profiles): make env auto persist optional

packages/platform-sdk-trx/src/networks/trx/testnet.ts, packages/platform-sdk-trx/src/services/transaction.ts
=> fix(trx): testnet explorer url

packages/platform-sdk-trx/src/dto/transaction.test.ts, packages/platform-sdk-trx/src/dto/transaction.ts, packages/platform-sdk-trx/src/services/transaction.ts, packages/platform-sdk-trx/test/fixtures/client/transactions.json
=> fix(trx): memo and block id extraction

examples/src/examples/transfer-trx.ts, packages/platform-sdk-profiles/test/fixtures/network.json, packages/platform-sdk/src/coins/network.models.ts
=> docs(trx): fix transaction amount

packages/platform-sdk-trx/src/networks/trx/mainnet.ts, packages/platform-sdk-trx/src/networks/trx/testnet.ts, packages/platform-sdk-trx/src/services/message.test.ts, packages/platform-sdk-trx/src/services/message.ts
=> feat(trx): message signing

packages/platform-sdk-profiles/src/drivers/memory/wallets/services/__snapshots__/serialiser.test.ts.snap, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts
=> fix(profiles): manually serialize wallet balance

packages/platform-sdk-nano/src/networks/nano/mainnet.ts, packages/platform-sdk-nano/src/services/identity/address.ts
=> feat(nano): derive address from public key

packages/platform-sdk-profiles/src/contracts/profiles/profile.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.dumper.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
=> refactor(profiles): make theme available unencrypted

packages/platform-sdk-ada/src/services/client.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.ts, packages/platform-sdk-xlm/src/dto/signed-transaction.ts
=> fix(xlm): isMultiSignatureRegistration returns false

packages/platform-sdk-ada/src/services/client.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.test.ts, packages/platform-sdk-profiles/src/drivers/memory/wallets/services/serialiser.ts, packages/platform-sdk-xlm/src/networks/xlm/mainnet.ts, packages/platform-sdk-xlm/src/networks/xlm/testnet.ts
=> fix(xlm): explorer links without trailing slash

examples/package.json, examples/pnpm-lock.yaml, examples/src/examples/transfer-ada.ts, examples/src/examples/transfer-ark.ts, examples/src/examples/transfer-trx.ts
=> docs: fix examples using signatory

examples/src/examples/sign-message-xlm.ts, examples/src/examples/transfer-ada.ts, examples/src/examples/transfer-ark.ts, examples/src/examples/transfer-trx.ts, examples/src/examples/transfer-xlm.ts, packages/platform-sdk-xlm/src/services/client.test.ts, packages/platform-sdk-xlm/src/services/client.ts
=> fix(xlm): proper way to fetch payments

packages/platform-sdk-profiles/src/contracts/profiles/profile.enum.ts, packages/platform-sdk-profiles/src/contracts/profiles/profile.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
https://github.com/ArkEcosystem/desktop-wallet/pull/3792
=> refactor(profiles): implement `IProfile#hasAcceptedManualInstallationDisclaimer`

packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts
This PR updates the JSDoc text of the wallet wif method.
=> fix(profiles): update wallet wif jsdoc

packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.validator.ts
=> fix(profiles): remove contact address name validation

packages/platform-sdk-btc-indexer/src/database.ts, packages/platform-sdk-btc-indexer/src/tx-parsing-helpers.test.ts, packages/platform-sdk-btc-indexer/src/tx-parsing-helpers.ts, packages/platform-sdk-btc-indexer/src/types.ts, packages/platform-sdk-support/src/bignumber.ts
=> chore(btc-indexer) more meaningful variable names

packages/platform-sdk-ada/src/services/identity/index.ts, packages/platform-sdk-ark/src/services/identity/address.test.ts, packages/platform-sdk-ark/src/services/identity/index.ts, packages/platform-sdk-ark/src/services/identity/keys.test.ts, packages/platform-sdk-ark/src/services/identity/private-key.test.ts, packages/platform-sdk-ark/src/services/identity/public-key.test.ts, packages/platform-sdk-ark/src/services/identity/wif.test.ts, packages/platform-sdk-ark/test/helpers.ts, packages/platform-sdk-atom/src/services/identity/index.ts, packages/platform-sdk-avax/src/services/identity/index.ts, packages/platform-sdk-btc/src/services/identity/index.ts, packages/platform-sdk-dot/src/services/identity/index.ts, packages/platform-sdk-egld/src/services/identity/index.ts, packages/platform-sdk-eos/src/services/identity/index.ts, packages/platform-sdk-eth/src/services/identity/index.ts, packages/platform-sdk-lsk/src/services/identity/index.ts, packages/platform-sdk-luna/src/services/identity/index.ts, packages/platform-sdk-nano/src/services/identity/index.ts, packages/platform-sdk-neo/src/services/identity/index.ts, packages/platform-sdk-sol/src/services/identity/index.ts, packages/platform-sdk-trx/src/services/identity/index.ts, packages/platform-sdk-xlm/src/services/identity/index.ts, packages/platform-sdk-xrp/src/services/identity/index.ts, packages/platform-sdk-zil/src/services/identity/index.ts, packages/platform-sdk/src/services/identity.ts, packages/platform-sdk/src/services/index.ts
https://app.clickup.com/t/kf4ka0
=> refactor: introduce `AbstractIdentityService`

packages/platform-sdk-btc-indexer/src/index.ts
=> fix(btc-indexer): use the schema file relative to running code

packages/platform-sdk-btc-indexer/prisma/schema.prisma
=> fix(btc-indexer): specify binary client targets

packages/platform-sdk-profiles/src/drivers/memory/services/delegate-service.ts
=> fix(profiles): set explorer link

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-ada/src/networks/shared.ts, packages/platform-sdk-ada/src/services/graphql-helpers.ts, packages/platform-sdk-ark/src/services/transaction.ts, packages/platform-sdk-btc-indexer/package.json, packages/platform-sdk/src/coins/config.ts
=> fix(ada): add transaction to manifest and fix braces

packages/platform-sdk-ada/src/networks/shared.ts
=> fix(ada): fix manifest for fee all

packages/platform-sdk-support/src/censor.test.ts, packages/platform-sdk-support/src/censor.ts
=> fix(support): case insensitive censoring

packages/platform-sdk-lsk/src/services/ledger.ts
Quick initial implementation for testing in DW.
=> feat(lsk): implement `LedgerService#scan`

packages/platform-sdk-profiles/src/contracts/profiles/profile.status.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.status.test.ts, packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.status.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts, packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.ts
=> feat(profiles): reset dirty status after persisting profile

packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.status.test.ts, packages/platform-sdk-profiles/src/environment/__snapshots__/env.test.ts.snap
=> test(profiles): update snapshots

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-lsk/package.json, packages/platform-sdk-lsk/src/networks/shared.ts, packages/platform-sdk-lsk/src/services/__snapshots__/ledger.test.ts.snap, packages/platform-sdk-lsk/src/services/ledger.test.ts, packages/platform-sdk-lsk/src/services/ledger.ts
=> feat(lisk): derive addresses and public keys from ledger

packages/platform-sdk-support/src/bignumber.test.ts, packages/platform-sdk-support/src/bignumber.ts
=> feat(support): implement `BigNumber#toSatoshi`

.github/workflows/cf.yml, .github/workflows/ci.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
=> ci: cancel previous workflows

packages/platform-sdk-btc-indexer/src/database.ts, packages/platform-sdk/src/coins/coin.ts
=> refactor(btc-indexer): use upserts for blocks, transactions and parts

packages/platform-sdk-ark/src/services/transaction.ts
Deriving the address early allows us to skip the nonce input for ledger signing, one less thing to do for the client.
=> refactor(ark): derive ledger address early to determine nonce

packages/platform-sdk/source/dto/signed-transaction.contract.ts
=> fix(sdk): export `SignedTransactionData#type` type

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/platform-sdk-btc-indexer/package.json, packages/platform-sdk-btc-indexer/source/client.ts, packages/platform-sdk-btc-indexer/source/database.ts, packages/platform-sdk-btc-indexer/source/factories.ts, packages/platform-sdk-btc-indexer/source/index.ts
=> fix(btc-indexer): indexing more robust

packages/platform-sdk-profiles/source/transaction.dto.test.ts, packages/platform-sdk-profiles/source/transaction.dto.ts
=> feat(profiles): implement `TransactionData#isReturn`

packages/platform-sdk-json-rpc/bin/meow.js, packages/platform-sdk-json-rpc/source/index.ts, packages/platform-sdk-json-rpc/source/methods/business.ts
Implements a business use-case as `business.withdrawal` which allows to withdraw all funds minus fee from a wallet.
=> feat(json-rpc): implement `business.withdrawal`

packages/platform-sdk-ark/source/fee.service.ts, packages/platform-sdk-ark/source/signed-transaction.dto.ts, packages/platform-sdk/source/dto/signed-transaction.contract.ts, packages/platform-sdk/source/dto/signed-transaction.ts
refactor transform method
`static` and `max` can use `maximumFee`
=> refactor(ark): use maximum fee as static and maximum

packages/platform-sdk-profiles/source/exchange-rate.service.ts
https://app.clickup.com/t/mxeu5h
=> fix(profiles): update hasFetchedHistoricalRates logic
